### ISSUE TITLE
After update only one speaker

### ISSUE THREAD

**Issue by xMAIKx** [ebaauw/homebridge-zp#102]
Hello, I have the following problem.  After the update from 0.3.18 to the current version, I only have one speaker in HomeKit.  I have 4 speakers in 2 groups.  I hope you can help me?  I had all 4 speakers in HomeKit before the update.

**Comment by ebaauw** [comment]
Please capture a debug log file and attach it, see https://github.com/ebaauw/homebridge-hue#debug-log-file.

**Comment by xMAIKx** [comment]
pi@raspberrypi:~ $ homebridge -D 2>&1 | tee homebridge.log
[2019-8-25 12:08:50] Loaded config.json with 0 accessories and 0 platforms.
[2019-8-25 12:08:50] ---
[2019-8-25 12:08:50] Plugin /usr/local/lib/node_modules/homebridge-lib package.json does not contain the keyword 'homebridge-plugin'.
[2019-8-25 12:08:50] Loaded plugin: homebridge-automation-switches
[2019-8-25 12:08:50] Registering platform 'homebridge-switches.AutomationSwitches'
[2019-8-25 12:08:50] ---
[2019-8-25 12:08:50] Loaded plugin: homebridge-bigAssFans
[2019-8-25 12:08:50] Registering platform 'homebridge-bigAssFans.BigAssFans'
[2019-8-25 12:08:50] Registering accessory 'homebridge-bigAssFan.BigAssFan'
[2019-8-25 12:08:50] ---
[2019-8-25 12:08:51] Loaded plugin: homebridge-calendar
[2019-8-25 12:08:51] Registering platform 'homebridge-calendar.Calendar'
[2019-8-25 12:08:51] ---
[2019-8-25 12:08:51] Loaded plugin: homebridge-callmonitor
[2019-8-25 12:08:51] Registering platform 'homebridge-callmonitor.CallMonitor'
[2019-8-25 12:08:51] ---
[2019-8-25 12:08:51] Loaded plugin: homebridge-delay-switch
[2019-8-25 12:08:51] Registering accessory 'homebridge-delay-switch.DelaySwitch'
[2019-8-25 12:08:51] ---
[2019-8-25 12:08:51] Loaded plugin: homebridge-dummy
[2019-8-25 12:08:51] Registering accessory 'homebridge-dummy.DummySwitch'
[2019-8-25 12:08:51] ---
[2019-8-25 12:08:51] Loaded plugin: homebridge-harmonyhub-plugin
[2019-8-25 12:08:51] Registering platform 'homebridge-harmonyhub-plugin.HarmonyHub'
[2019-8-25 12:08:51] ---
[2019-8-25 12:08:52] Loaded plugin: homebridge-http-webhooks
[2019-8-25 12:08:52] Registering platform 'homebridge-http-webhooks.HttpWebHooks'
[2019-8-25 12:08:52] Registering accessory 'homebridge-http-webhooks.HttpWebHookSensor'
[2019-8-25 12:08:52] Registering accessory 'homebridge-http-webhooks.HttpWebHookSwitch'
[2019-8-25 12:08:52] Registering accessory 'homebridge-http-webhooks.HttpWebHookPushButton'
[2019-8-25 12:08:52] Registering accessory 'homebridge-http-webhooks.HttpWebHookLight'
[2019-8-25 12:08:52] Registering accessory 'homebridge-http-webhooks.HttpWebHookThermostat'
[2019-8-25 12:08:52] Registering accessory 'homebridge-http-webhooks.HttpWebHookOutlet'
[2019-8-25 12:08:52] Registering accessory 'homebridge-http-webhooks.HttpWebHookSecurity'
[2019-8-25 12:08:52] Registering accessory 'homebridge-http-webhooks.HttpWebHookGarageDoorOpener'
[2019-8-25 12:08:52] Registering accessory 'homebridge-http-webhooks.HttpWebHookStatelessSwitch'
[2019-8-25 12:08:52] Registering accessory 'homebridge-http-webhooks.HttpWebHookLockMechanism'
[2019-8-25 12:08:52] Registering accessory 'homebridge-http-webhooks.HttpWebHookWindowCovering'
[2019-8-25 12:08:52] ---
[2019-8-25 12:08:52] Plugin /usr/local/lib/node_modules/homebridge-hue requires Node version of ^10.16.0 which does not satisfy the current Node version of v10.15.0. You may need to upgrade your installation of Node.
[2019-8-25 12:08:53] Loaded plugin: homebridge-hue
[2019-8-25 12:08:53] Registering platform 'homebridge-hue.Hue'
[2019-8-25 12:08:53] ---
[2019-8-25 12:08:53] Loaded plugin: homebridge-ifttt
[2019-8-25 12:08:53] Registering platform 'homebridge-ifttt.IFTTT'
[2019-8-25 12:08:53] ---
[2019-8-25 12:08:54] Loaded plugin: homebridge-mi-aqara
[2019-8-25 12:08:54] Registering platform 'homebridge-mi-aqara.MiAqaraPlatform'
[2019-8-25 12:08:54] ---
[2019-8-25 12:08:54] Loaded plugin: homebridge-netatmo
[2019-8-25 12:08:54] Registering platform 'homebridge-netatmo.netatmo'
[2019-8-25 12:08:54] ---
[2019-8-25 12:08:55] Loaded plugin: homebridge-nukiio
[2019-8-25 12:08:55] Registering platform 'homebridge-nukiio.NukiBridge'
[2019-8-25 12:08:55] Registering accessory 'homebridge-nukiio.NukiLock'
[2019-8-25 12:08:55] Registering accessory 'homebridge-nukiio.NukiBridgeMaintainanceSwitch'
[2019-8-25 12:08:55] ---
[2019-8-25 12:08:55] Loaded plugin: homebridge-suncalc
[2019-8-25 12:08:55] Registering accessory 'homebridge-suncalc.Suncalc'
[2019-8-25 12:08:55] ---
[2019-8-25 12:08:55] Loaded plugin: homebridge-telegram
[2019-8-25 12:08:55] Registering platform 'homebridge-telegram.Telegram'
[2019-8-25 12:08:55] ---
[2019-8-25 12:08:55] Loaded plugin: homebridge-wol
[2019-8-25 12:08:55] Registering accessory 'homebridge-wol.NetworkDevice'
[2019-8-25 12:08:55] ---
[2019-8-25 12:08:56] Loaded plugin: homebridge-xiaomi-mi-robot-vacuum
[2019-8-25 12:08:56] Registering accessory 'homebridge-xiaomi-mi-robot-vacuum.MiRobotVacuum'
[2019-8-25 12:08:56] ---
[2019-8-25 12:08:56] Plugin /usr/local/lib/node_modules/homebridge-zp requires Node version of ^10.16.3 which does not satisfy the current Node version of v10.15.0. You may need to upgrade your installation of Node.
[2019-8-25 12:08:56] Loaded plugin: homebridge-zp
[2019-8-25 12:08:57] Registering platform 'homebridge-lib.Lib'
[2019-8-25 12:08:57] Registering platform 'homebridge-zp.ZP'
[2019-8-25 12:08:57] ---
[2019-8-25 12:08:57] Loading 0 platforms...
[2019-8-25 12:08:57] Loading 0 accessories...
Load homebridge-switches.AutomationSwitches
[2019-8-25 12:08:57] [homebridge-switches.AutomationSwitches] AutomationSwitchesPlatform Plugin Loaded - Version 3.2.1
Load homebridge-bigAssFans.BigAssFans
Load homebridge-calendar.Calendar
[2019-8-25 12:08:57] [homebridge-calendar.Calendar] CalendarPlatform Plugin Loaded - version 0.4.0
Load homebridge-callmonitor.CallMonitor
[2019-8-25 12:08:57] [homebridge-callmonitor.CallMonitor] CallMonitor Platform Plugin Loaded
Load homebridge-harmonyhub-plugin.HarmonyHub
[2019-8-25 12:08:57] [homebridge-harmonyhub-plugin.HarmonyHub] {Plugin} cannot setup HarmonyHub because config is missing
Load homebridge-mi-aqara.MiAqaraPlatform
Load homebridge-telegram.Telegram
[2019-8-25 12:08:57] [homebridge-telegram.Telegram] TelegramPlatform Plugin Loaded
Load homebridge-zp.ZP
Setup Payload:
X-HM://0023ISYWYEJAP
Scan this code with your HomeKit app on your iOS device to pair   Or enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
[2019-8-25 12:08:57] Homebridge is running on port 51826.

**Comment by xMAIKx** [comment]
pi@raspberrypi:~ $ sudo homebridge
[2019-8-25 12:15:32] Loaded config.json with 6 accessories and 13 platforms.
[2019-8-25 12:15:32] ---
[2019-8-25 12:15:32] Plugin /usr/local/lib/node_modules/homebridge-lib package.json does not contain the keyword 'homebridge-plugin'.
[2019-8-25 12:15:32] Loaded plugin: homebridge-automation-switches
[2019-8-25 12:15:32] Registering platform 'homebridge-switches.AutomationSwitches'
[2019-8-25 12:15:32] ---
[2019-8-25 12:15:32] Loaded plugin: homebridge-bigAssFans
[2019-8-25 12:15:32] Registering platform 'homebridge-bigAssFans.BigAssFans'
[2019-8-25 12:15:32] Registering accessory 'homebridge-bigAssFan.BigAssFan'
[2019-8-25 12:15:32] ---
[2019-8-25 12:15:33] Loaded plugin: homebridge-calendar
[2019-8-25 12:15:33] Registering platform 'homebridge-calendar.Calendar'
[2019-8-25 12:15:33] ---
[2019-8-25 12:15:33] Loaded plugin: homebridge-callmonitor
[2019-8-25 12:15:33] Registering platform 'homebridge-callmonitor.CallMonitor'
[2019-8-25 12:15:33] ---
[2019-8-25 12:15:33] Loaded plugin: homebridge-delay-switch
[2019-8-25 12:15:33] Registering accessory 'homebridge-delay-switch.DelaySwitch'
[2019-8-25 12:15:33] ---
[2019-8-25 12:15:33] Loaded plugin: homebridge-dummy
[2019-8-25 12:15:33] Registering accessory 'homebridge-dummy.DummySwitch'
[2019-8-25 12:15:33] ---
[2019-8-25 12:15:33] Loaded plugin: homebridge-harmonyhub-plugin
[2019-8-25 12:15:33] Registering platform 'homebridge-harmonyhub-plugin.HarmonyHub'
[2019-8-25 12:15:33] ---
[2019-8-25 12:15:34] Loaded plugin: homebridge-http-webhooks
[2019-8-25 12:15:34] Registering platform 'homebridge-http-webhooks.HttpWebHooks'
[2019-8-25 12:15:34] Registering accessory 'homebridge-http-webhooks.HttpWebHookSensor'
[2019-8-25 12:15:34] Registering accessory 'homebridge-http-webhooks.HttpWebHookSwitch'
[2019-8-25 12:15:34] Registering accessory 'homebridge-http-webhooks.HttpWebHookPushButton'
[2019-8-25 12:15:34] Registering accessory 'homebridge-http-webhooks.HttpWebHookLight'
[2019-8-25 12:15:34] Registering accessory 'homebridge-http-webhooks.HttpWebHookThermostat'
[2019-8-25 12:15:34] Registering accessory 'homebridge-http-webhooks.HttpWebHookOutlet'
[2019-8-25 12:15:34] Registering accessory 'homebridge-http-webhooks.HttpWebHookSecurity'
[2019-8-25 12:15:34] Registering accessory 'homebridge-http-webhooks.HttpWebHookGarageDoorOpener'
[2019-8-25 12:15:34] Registering accessory 'homebridge-http-webhooks.HttpWebHookStatelessSwitch'
[2019-8-25 12:15:34] Registering accessory 'homebridge-http-webhooks.HttpWebHookLockMechanism'
[2019-8-25 12:15:34] Registering accessory 'homebridge-http-webhooks.HttpWebHookWindowCovering'
[2019-8-25 12:15:34] ---
[2019-8-25 12:15:34] Plugin /usr/local/lib/node_modules/homebridge-hue requires Node version of ^10.16.0 which does not satisfy the current Node version of v10.15.0. You may need to upgrade your installation of Node.
[2019-8-25 12:15:35] Loaded plugin: homebridge-hue
[2019-8-25 12:15:35] Registering platform 'homebridge-hue.Hue'
[2019-8-25 12:15:35] ---
[2019-8-25 12:15:35] Loaded plugin: homebridge-ifttt
[2019-8-25 12:15:35] Registering platform 'homebridge-ifttt.IFTTT'
[2019-8-25 12:15:35] ---
[2019-8-25 12:15:36] Loaded plugin: homebridge-mi-aqara
[2019-8-25 12:15:36] Registering platform 'homebridge-mi-aqara.MiAqaraPlatform'
[2019-8-25 12:15:36] ---
[2019-8-25 12:15:37] Loaded plugin: homebridge-netatmo
[2019-8-25 12:15:37] Registering platform 'homebridge-netatmo.netatmo'
[2019-8-25 12:15:37] ---
[2019-8-25 12:15:37] Loaded plugin: homebridge-nukiio
[2019-8-25 12:15:37] Registering platform 'homebridge-nukiio.NukiBridge'
[2019-8-25 12:15:37] Registering accessory 'homebridge-nukiio.NukiLock'
[2019-8-25 12:15:37] Registering accessory 'homebridge-nukiio.NukiBridgeMaintainanceSwitch'
[2019-8-25 12:15:37] ---
[2019-8-25 12:15:37] Loaded plugin: homebridge-suncalc
[2019-8-25 12:15:37] Registering accessory 'homebridge-suncalc.Suncalc'
[2019-8-25 12:15:37] ---
[2019-8-25 12:15:37] Loaded plugin: homebridge-telegram
[2019-8-25 12:15:37] Registering platform 'homebridge-telegram.Telegram'
[2019-8-25 12:15:37] ---
[2019-8-25 12:15:37] Loaded plugin: homebridge-wol
[2019-8-25 12:15:37] Registering accessory 'homebridge-wol.NetworkDevice'
[2019-8-25 12:15:37] ---
[2019-8-25 12:15:38] Loaded plugin: homebridge-xiaomi-mi-robot-vacuum
[2019-8-25 12:15:38] Registering accessory 'homebridge-xiaomi-mi-robot-vacuum.MiRobotVacuum'
[2019-8-25 12:15:38] ---
[2019-8-25 12:15:38] Plugin /usr/local/lib/node_modules/homebridge-zp requires Node version of ^10.16.3 which does not satisfy the current Node version of v10.15.0. You may need to upgrade your installation of Node.
[2019-8-25 12:15:39] Loaded plugin: homebridge-zp
[2019-8-25 12:15:39] Registering platform 'homebridge-lib.Lib'
[2019-8-25 12:15:39] Registering platform 'homebridge-zp.ZP'
[2019-8-25 12:15:39] ---
[2019-8-25 12:15:39] Loading 13 platforms...
[2019-8-25 12:15:39] [Calendar] Initializing Calendar platform...
[2019-8-25 12:15:39] [Calendar] CalendarPlatform Plugin Loaded - version 0.4.0
[2019-8-25 12:15:39] [Calendar] Found calendar in config: "Abfall"
[2019-8-25 12:15:39] [Calendar] Pushing calendar sensor 'Abfall' state 0 - value 0
[2019-8-25 12:15:39] [Calendar] Pushing calendar sensor 'Restabfall' state 0 - value 0
[2019-8-25 12:15:39] [Calendar] Pushing calendar sensor 'Gelber Sack' state 0 - value 0
[2019-8-25 12:15:39] [Calendar] Polling calendar Abfall has started.
[2019-8-25 12:15:39] [Calendar] Updating calendar Abfall
[2019-8-25 12:15:39] [Calendar] Found calendar in config: "Geburtstag"
[2019-8-25 12:15:39] [Calendar] Pushing calendar sensor 'Geburtstag' state 0 - value 0
[2019-8-25 12:15:39] [Calendar] Polling calendar Geburtstag has started.
[2019-8-25 12:15:39] [Calendar] Updating calendar Geburtstag
[2019-8-25 12:15:39] [Calendar] Found calendar in config: "Urlaub"
[2019-8-25 12:15:39] [Calendar] Pushing calendar sensor 'Urlaub' state 0 - value 0
[2019-8-25 12:15:39] [Calendar] Polling calendar Urlaub has started.
[2019-8-25 12:15:39] [Calendar] Updating calendar Urlaub
[2019-8-25 12:15:39] [Calendar] Initializing platform accessory 'Abfall'...
[2019-8-25 12:15:39] [Calendar] Initializing platform accessory 'Geburtstag'...
[2019-8-25 12:15:39] [Calendar] Initializing platform accessory 'Urlaub'...
[2019-8-25 12:15:39] [Big Ass Fan] Initializing BigAssFans platform...
[2019-8-25 12:15:39] [Big Ass Fan] Big Ass Fans Platform Init
[2019-8-25 12:15:39] [IFTTT] Initializing IFTTT platform...
[2019-8-25 12:15:39] [IFTTT] Loading accessories...
[2019-8-25 12:15:39] [IFTTT] Found: Duftlampe
[2019-8-25 12:15:39] [IFTTT] Loading service: Duftlampe, subtype: Diffuser_onDiffuser_off, RestoredState: false
[2019-8-25 12:15:39] [IFTTT] Found: Wasserkocher Kueche
[2019-8-25 12:15:39] [IFTTT] Loading service: Wasserkocher, subtype: Wasserkocher_on
[2019-8-25 12:15:39] [IFTTT] Found: Alarmanlage ZU Hause
[2019-8-25 12:15:39] [IFTTT] Loading service: Alarmanlage, subtype: SchalterAlarmanlageEingeschaltetZuHauseSchalterAlarmanlageAusgeschaltetZuHause
[2019-8-25 12:15:39] [IFTTT] Found: Push Alarm Zu Hause
[2019-8-25 12:15:39] [IFTTT] Loading service: Push Alarm, subtype: PushAlarmAusgloestZuHausePushAlarmDeaktiviertZuHause
[2019-8-25 12:15:39] [IFTTT] Initializing platform accessory 'Duftlampe'...
[2019-8-25 12:15:39] [IFTTT] Initializing platform accessory 'Wasserkocher Kueche'...
[2019-8-25 12:15:39] [IFTTT] Initializing platform accessory 'Alarmanlage ZU Hause'...
[2019-8-25 12:15:39] [IFTTT] Initializing platform accessory 'Push Alarm Zu Hause'...
[2019-8-25 12:15:39] [Telegram] Initializing Telegram platform...
[2019-8-25 12:15:39] [Telegram] TelegramPlatform Plugin Loaded
[2019-8-25 12:15:39] [Telegram] Found bot in config: "Push Nachrichten Zu Hause"
[2019-8-25 12:15:39] [Telegram] Initializing platform accessory 'Push Nachrichten Zu Hause'...
[2019-8-25 12:15:39] [homebridge-harmonyhub-plugin] Initializing HarmonyHub platform...
[2019-8-25 12:15:39] [MiAqaraPlatform] Initializing MiAqaraPlatform platform...
[2019-8-25 12:15:39] [MiAqaraPlatform] [INFO]**************************************************************
[2019-8-25 12:15:39] [MiAqaraPlatform] [INFO]           MiAqaraPlatform v0.8.0 By YinHang
[2019-8-25 12:15:39] [MiAqaraPlatform] [INFO]  GitHub: https://github.com/YinHangCode/homebridge-mi-aqara  
[2019-8-25 12:15:39] [MiAqaraPlatform] [INFO]                                         QQ Group: xxxxxxxxx 
[2019-8-25 12:15:39] [MiAqaraPlatform] [INFO]**************************************************************
[2019-8-25 12:15:39] [MiAqaraPlatform] [INFO]start success...
[2019-8-25 12:15:39] [MiAqaraPlatform] [INFO]config gateways: 3xxxxxxxxxxxx
[2019-8-25 12:15:39] [MiAqaraPlatform] [INFO]binding to the default interface
[2019-8-25 12:15:39] [HttpWebHooks] Initializing HttpWebHooks platform...
[2019-8-25 12:15:39] [HttpWebHooks] Initializing platform accessory 'Sonos Playlist Guardians'...
[2019-8-25 12:15:39] [HttpWebHooks] Initializing platform accessory 'Sonos Say Aniko'...
[2019-8-25 12:15:39] [HttpWebHooks] Initializing platform accessory 'Sonos Say Maik'...
[2019-8-25 12:15:39] [HttpWebHooks] Initializing platform accessory 'Sonos Say Popo'...
[2019-8-25 12:15:39] [HttpWebHooks] Initializing platform accessory 'Sonos Say morgen'...
[2019-8-25 12:15:39] [HttpWebHooks] Initializing platform accessory 'Sonos Say federn'...
[2019-8-25 12:15:39] [HttpWebHooks] Initializing platform accessory 'Sonos Say Anruf'...
[2019-8-25 12:15:39] [HttpWebHooks] Initializing platform accessory 'Sonos Say Aniko kommt'...
[2019-8-25 12:15:39] [HttpWebHooks] Initializing platform accessory 'Sonos Say Eindringling'...
[2019-8-25 12:15:39] [HttpWebHooks] Initializing platform accessory 'Sonos Say Geburtstag'...
[2019-8-25 12:15:39] [HttpWebHooks] Initializing platform accessory 'Sonos Radio Hamburg'...
[2019-8-25 12:15:39] [HttpWebHooks] Initializing platform accessory 'Sicherheitswarnung'...
[2019-8-25 12:15:39] [HttpWebHooks] Started server for webhooks on port '51828'.
[2019-8-25 12:15:39] [CallMonitor] Initializing CallMonitor platform...
[2019-8-25 12:15:39] [CallMonitor] CallMonitor Platform Plugin Loaded
[2019-8-25 12:15:39] [CallMonitor] Found device in config: "undefined"
[2019-8-25 12:15:39] [CallMonitor] Initializing platform accessory 'AVM Fritz!Box 6490'...
[2019-8-25 12:15:39] [Hue] Initializing Hue platform...
[2019-8-25 12:15:39] [Hue] homebridge-hue v0.11.30, node v10.15.0, homebridge v0.4.50
[2019-8-25 12:15:39] [Hue] warning: not using recommended node version v10.16.0 LTS
[2019-8-25 12:15:39] [ZP] Initializing ZP platform...
[2019-8-25 12:15:39] [ZP] homebridge-zp v1.0.10, node 10.15.0, homebridge v0.4.50, homebridge-lib v4.4.4
[2019-8-25 12:15:39] [ZP] warning: 10.15.0: not using recommended node v10.16.3 LTS
[2019-8-25 12:15:39] [AutomationSwitches] Initializing AutomationSwitches platform...
[2019-8-25 12:15:39] [AutomationSwitches] AutomationSwitchesPlatform Plugin Loaded - Version 3.2.1
[2019-8-25 12:15:39] [AutomationSwitches] Found automation switch in config: "Automation Switch #1"
[2019-8-25 12:15:39] [AutomationSwitches] Found automation switch in config: "Automation Briefkasten #2"
[2019-8-25 12:15:39] [AutomationSwitches] Found automation switch in config: "Alarmsystem"
[2019-8-25 12:15:39] [AutomationSwitches] Switch Alarmsystem is stored in file SecuritySystem.565840B90FC8.json
[2019-8-25 12:15:39] [AutomationSwitches] Initializing platform accessory 'Automation Switch #1'...
[2019-8-25 12:15:39] [AutomationSwitches] Initializing platform accessory 'Automation Briefkasten #2'...
[2019-8-25 12:15:39] [AutomationSwitches] Initializing platform accessory 'Alarmsystem'...
[2019-8-25 12:15:39] [netatmo platform] Initializing netatmo platform...
[2019-8-25 12:15:39] [Nuki] Initializing NukiBridge platform...
[2019-8-25 12:15:39] [Nuki] Initializing Nuki bridge 'http://192.1xxxxxxxx'...
[2019-8-25 12:15:39] [Nuki] Started server for webhooks on port '51827'.
[2019-8-25 12:15:39] [Nuki] Adding webhook for plugin to bridge...
[2019-8-25 12:15:39] [Nuki] Initialized Nuki bridge.
[2019-8-25 12:15:39] [Nuki] Initializing platform accessory 'Haustür'...
[2019-8-25 12:15:39] Loading 6 accessories...
[2019-8-25 12:15:39] [Vacuum Cleaner] Initializing MiRobotVacuum accessory...
[2019-8-25 12:15:39] [Suncalc] Initializing Suncalc accessory...
[2019-8-25 12:15:39] [Suncalc] Currently Daytime(3). Sunset is at 20:24:50
[2019-8-25 12:15:39] [Suncalc] Sunset time will be offset by -45 minute(s)
[2019-8-25 12:15:39] [PC] Initializing NetworkDevice accessory...
[2019-8-25 12:15:39] [DelaySwitch] Initializing DelaySwitch accessory...
[2019-8-25 12:15:40] [Maik Switch] Initializing DummySwitch accessory...
[2019-8-25 12:15:40] [Maik Switch] Setting switch to true
[2019-8-25 12:15:40] [Aniko Switch] Initializing DummySwitch accessory...
[2019-8-25 12:15:40] [Aniko Switch] Setting switch to true
Load homebridge-switches.AutomationSwitches
[2019-8-25 12:15:40] [homebridge-switches.AutomationSwitches] AutomationSwitchesPlatform Plugin Loaded - Version 3.2.1
Load homebridge-calendar.Calendar
[2019-8-25 12:15:40] [homebridge-calendar.Calendar] CalendarPlatform Plugin Loaded - version 0.4.0
Load homebridge-callmonitor.CallMonitor
[2019-8-25 12:15:40] [homebridge-callmonitor.CallMonitor] CallMonitor Platform Plugin Loaded
Load homebridge-telegram.Telegram
[2019-8-25 12:15:40] [homebridge-telegram.Telegram] TelegramPlatform Plugin Loaded
[2019-8-25 12:15:40] [Big Ass Fan] Ventilator Schlafzimmer  Configure Accessory 0a802e38-7d16-xxxxxxxxxxxxxxxxxxxx
[2019-8-25 12:15:40] [Big Ass Fan] DidFinishLaunching
[2019-8-25 12:15:40] [ZP] restored 1 accessories from cache
[2019-8-25 12:15:40] [MiAqaraPlatform] [INFO]Aqara LAN protocol server is listening on port: 9898
(node:18902) UnhandledPromiseRejectionWarning: TypeError: events.once is not a function
    at ZpPlatform._main (/usr/local/lib/node_modules/homebridge-zp/node_modules/homebridge-lib/lib/Platform.js:241:18)
    at API.emit (events.js:187:15)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:103:13)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
(node:18902) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:18902) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[2019-8-25 12:15:40] [CallMonitor] Connected to AVM Fritz!Box 6490
[2019-8-25 12:15:40] [ZP] error: TypeError: events.once is not a function
    at ZpPlatform.createZpClient (/usr/local/lib/node_modules/homebridge-zp/lib/ZpPlatform.js:238:22)
    at ZpPlatform.handleUpnpMessage (/usr/local/lib/node_modules/homebridge-zp/lib/ZpPlatform.js:170:18)
    at ZpPlatform.emit (events.js:182:13)
    at ZpPlatform.emit (/usr/local/lib/node_modules/homebridge-zp/node_modules/homebridge-lib/lib/Delegate.js:148:13)
    at UpnpClient._upnpMonitor.on (/usr/local/lib/node_modules/homebridge-zp/node_modules/homebridge-lib/lib/Platform.js:538:12)
    at UpnpClient.emit (events.js:182:13)
    at Socket.socket.on (/usr/local/lib/node_modules/homebridge-zp/node_modules/homebridge-lib/lib/UpnpClient.js:148:14)
    at Socket.emit (events.js:182:13)
    at UDP.onMessage [as onmessage] (dgram.js:628:8)
[2019-8-25 12:15:40] [Nuki] Send request to Nuki bridge 'http://192.1xxxxxxxxx' on '/callback/list' with '{"token":"Xxxxxx"}'.
[2019-8-25 12:15:41] [ZP] listening on http://192.168.Xxxxxxxxxxx/notify
[2019-8-25 12:15:41] [ZP] RINCON_7828CXxxxxxx [Bad2]: associated zone player
[2019-8-25 12:15:41] [ZP] warning: heartbeat 0, drift 404
[2019-8-25 12:15:42] [Calendar] Pushing calendar sensor 'Geburtstag' state 0 - value 0
[2019-8-25 12:15:42] [Calendar] No events to schedule.
[2019-8-25 12:15:42] [Hue] warning: latest version: homebridge-hue v0.11.35
[2019-8-25 12:15:42] [Calendar] Pushing calendar sensor 'Urlaub' state 0 - value 0
[2019-8-25 12:15:42] [Calendar] No events to schedule.
[2019-8-25 12:15:42] [Calendar] Pushing calendar sensor 'Abfall' state 0 - value 0
[2019-8-25 12:15:42] [Calendar] Pushing calendar sensor 'Restabfall' state 0 - value 0
[2019-8-25 12:15:42] [Calendar] Pushing calendar sensor 'Gelber Sack' state 0 - value 0
[2019-8-25 12:15:42] [Calendar] Scheduling next action in 42247516ms
[2019-8-25 12:15:42] [Nuki] Request to Nuki bridge 'http://192.16Xxxxxxxxxx' finished with status code '200' and body '{"callbacks": [{"id": 1, "url": "http://192.168.1Xxxxxxxxx/"},{"id": 2, "url": "http://192.168.1Xxxxxxxxxxx/"}]}'. null
[2019-8-25 12:15:42] [Nuki] Webhook for plugin already exists.
[2019-8-25 12:15:42] [ZP] warning: heartbeat 1, drift 472
[2019-8-25 12:15:42] [ZP] found 4 zone players in 4 zones
[2019-8-25 12:15:42] [ZP] ├─ Bad2
[2019-8-25 12:15:42] [ZP] │  └─ RINCON_7828CA0AA442xxxxx [Bad2]: Sonos One (S13) (master, airPlay)
[2019-8-25 12:15:42] [ZP] ├─ Kueche
[2019-8-25 12:15:42] [ZP] │  └─ RINCON_B8E937B09BExxxxxx [Kueche]: Sonos Play:1 (S1) (master)
[2019-8-25 12:15:42] [ZP] ├─ Schlafzimmer
[2019-8-25 12:15:42] [ZP] │  └─ RINCON_7828CA02F5XXXXXX [Schlafzimmer]: Sonos One (S13) (master, airPlay)
[2019-8-25 12:15:42] [ZP] └─ Wohnzimmer
[2019-8-25 12:15:42] [ZP]    └─ RINCON_B8E93792AXxxx [Wohnzimmer]: Sonos Connect (ZP90) (master, audioIn)
(node:18902) UnhandledPromiseRejectionWarning: TypeError: events.once is not a function
    at ZpPlatform.logTopology (/usr/local/lib/node_modules/homebridge-zp/lib/ZpPlatform.js:407:28)
    at ZpPlatform.createZpClient (/usr/local/lib/node_modules/homebridge-zp/lib/ZpPlatform.js:288:14)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:18902) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
[2019-8-25 12:15:43] [netatmo platform] Initializing platform accessory 'Lütjenseerstraße Netatmo Innen'...
[2019-8-25 12:15:43] [netatmo platform] Initializing platform accessory 'Lütjenseerstraße Terrasse'...
[2019-8-25 12:15:43] [homebridge-harmonyhub-plugin] {HarmonyHub} Found <1> hubs
[2019-8-25 12:15:43] [homebridge-harmonyhub-plugin] {HarmonyHub} <027414b1-1221-4202-b978-53XXXXXXXXXXXX> <Harmony Hub>
[2019-8-25 12:15:44] [homebridge-harmonyhub-plugin] {HarmonyHub} create new client for <Harmony Hub>
[2019-8-25 12:15:44] [Big Ass Fan] Found a light for: Ventilator Schlafzimmer  Fan Light
[2019-8-25 12:15:45] [homebridge-harmonyhub-plugin] {HarmonyHub} Found <6> activities: <Wiedergabe PS3, Tv, SHIELD TV, RTL, Mediaplayer, Wohnzimmer Sonos>
[2019-8-25 12:15:47] [Hue] Philips hue: Philips BSB002 bridge v1933XXXXXX, api v1.33.0
[2019-8-25 12:15:47] [Hue] Philips hue: warning: not using recommended Hue bridge api version 1.32.0
[2019-8-25 12:15:47] [Hue] Philips hue: 4 accessories
[2019-8-25 12:15:47] [Hue] masked debug info dumped to /root/.homebridge/homebridge-hue.json.gz
[2019-8-25 12:15:47] [Hue] Initializing platform accessory 'Philips hue'...
[2019-8-25 12:15:47] [Hue] Philips hue: 2 services
[2019-8-25 12:15:47] [Hue] Initializing platform accessory 'Maik '...
[2019-8-25 12:15:47] [Hue] Initializing platform accessory 'XFDAnybodyHome'...
[2019-8-25 12:15:47] [Hue] Initializing platform accessory 'Aniko '...
Setup Payload:
X-HM://0023ISYXXXXXXXX
Scan this code with your HomeKit app on your iOS device to pair with Homebridge:

**Comment by xMAIKx** [comment]
I have solved the problem now.  With the current Node and Npm version I have all the speakers back in Homekit.  But now I have the problem that I can leave the group with the second switch but not come back with the speaker in the group.  With the version 0.3.18 went without problems.  I ask for help.

**Comment by ebaauw** [comment]
You need to set _Sonos Coordinator_ of the zone player you want to group to (in Eve, as this is a custom characteristic).  You can also set this from Apple's Home app by selecting _View TV Settings_ under _Settings_ for the TV accessory.  Once, you've set the target coordinator, it will stick across homebridge restarts.  See https://github.com/ebaauw/homebridge-zp/issues/94#issuecomment-516969748.
