### ISSUE TITLE
HomeKit not showing Speakers after latest update. 

### ISSUE THREAD

**Issue by kaspersoerensen** [ebaauw/homebridge-zp#109]
Not sure if this is related to #108 , but since I updated to the latest version of `homebridge-zp` I get the following error, when starting up `homebridge` on my RPI-3:

```
[2019-10-14 14:21:49] [Sonos] restored 1 accessories from cache
[2019-10-14 14:21:49] Homebridge is running on port 51826.
(node:4420) UnhandledPromiseRejectionWarning: TypeError: events.once is not a function
    at ZpPlatform._main (/usr/lib/node_modules/homebridge-zp/node_modules/homebridge-lib/lib/Platform.js:241:18)
    at emitNone (events.js:106:13)
    at API.emit (events.js:208:7)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:103:13)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
(node:4420) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4420) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[2019-10-14 14:21:49] [Sonos] listening on http://10.0.1.2:40061/notify
[2019-10-14 14:21:49] [Sonos] RINCON_949F3EC4D7BD01400 [Stue]: associated zone player
[2019-10-14 14:21:49] [Sonos] error: TypeError: events.once is not a function
    at ZpPlatform.createZpClient (/usr/lib/node_modules/homebridge-zp/lib/ZpPlatform.js:238:22)
    at ZpPlatform.handleUpnpMessage (/usr/lib/node_modules/homebridge-zp/lib/ZpPlatform.js:170:18)
    at emitTwo (events.js:126:13)
    at ZpPlatform.emit (events.js:214:7)
    at ZpPlatform.emit (/usr/lib/node_modules/homebridge-zp/node_modules/homebridge-lib/lib/Delegate.js:148:13)
    at UpnpClient._upnpMonitor.on (/usr/lib/node_modules/homebridge-zp/node_modules/homebridge-lib/lib/Platform.js:538:12)
    at emitThree (events.js:136:13)
    at UpnpClient.emit (events.js:217:7)
    at Socket.socket.on (/usr/lib/node_modules/homebridge-zp/node_modules/homebridge-lib/lib/UpnpClient.js:148:14)
    at emitTwo (events.js:126:13)
    at Socket.emit (events.js:214:7)
    at UDP.onMessage [as onmessage] (dgram.js:659:8)
[2019-10-14 14:21:49] [Sonos] found 3 zone players in 3 zones
[2019-10-14 14:21:49] [Sonos] ├─ Køkken
[2019-10-14 14:21:49] [Sonos] │  └─ RINCON_7828CAF5C83001400 [Køkken]: Sonos One (S18) (master, airPlay)
[2019-10-14 14:21:49] [Sonos] ├─ Soveværelse
[2019-10-14 14:21:49] [Sonos] │  └─ RINCON_7828CAE2E9EC01400 [Soveværelse]: Sonos One (S18) (master, airPlay)
[2019-10-14 14:21:49] [Sonos] └─ Stue
[2019-10-14 14:21:49] [Sonos]    └─ RINCON_949F3EC4D7BD01400 [Stue]: Sonos Beam (S14) (master, airPlay, tvIn)
(node:4420) UnhandledPromiseRejectionWarning: TypeError: events.once is not a function
    at ZpPlatform.logTopology (/usr/lib/node_modules/homebridge-zp/lib/ZpPlatform.js:407:28)
    at ZpPlatform.createZpClient (/usr/lib/node_modules/homebridge-zp/lib/ZpPlatform.js:288:14)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
(node:4420) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
```

The speakers does not show up in Homekit anymore unfortunatly.

**Comment by ebaauw** [comment]
You’re using on old version of NodeJS that doesn’t support `events.once`.  See #103, #105.

**Comment by kaspersoerensen** [comment]
Ah yes. Sorry. Thank you for the great work on this plugin!
