### ISSUE TITLE
Homebridge Service Won't Start on Hoobs after latest update

### ISSUE THREAD

**Issue by turnepf** [ebaauw/homebridge-zp#130]
#### Issue

After installing the latest zp updates yesterday, Homebridge wouldn't start on HOOBS. (It worked great before this update.) I uninstalled zp and Homebridge started fine. Reinstalled, and Homebridge wouldn't start. I've included the logs below which indicates some compatibility issues. 

#### Log Messages

```
[Homebridge] [4/12/2020, 10:32:54 AM] Got SIGINT, shutting down service...
npm
 WARN notsup Unsupported engine for homebridge-zp@1.0.26: wanted: {"homebridge":"~0.4.53","node":"^12.16.2"} (current: {"node":"10.18.0","npm":"6.13.4"})
npm WARN notsup
 Not compatible with your version of node/npm: homebridge-zp@1.0.26
npm WARN notsup Unsupported engine for homebridge-lib@4.5.7: wanted: {"homebridge":"~0.4.53","node":"^12.16.2"} (current: {"node":"10.18.0","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: homebridge-lib@4.5.7
npm WARN winston-daily-rotate-file@4.4.2 requires a peer of winston@^3 but none is installed. You must install peer dependencies yourself.
+ homebridge-zp@1.0.26
added 15 packages from 56 contributors, removed 2 packages and audited 1389 packages in 15.692s

19 packages are looking for funding
  run `npm fund` for details
found 1 low severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
[4/12/2020, 10:33:14 AM] Installed "homebridge-zp" package.
[Homebridge] [4/12/2020, 10:33:16 AM] Loaded config.json with 0 accessories and 5 platforms.
[Homebridge] [4/12/2020, 10:33:19 AM] Loaded plugin: "homebridge-camera-ffmpeg"
[Homebridge] [4/12/2020, 10:33:19 AM] Registering platform "homebridge-camera-ffmpeg.Camera-ffmpeg"
[Homebridge] [4/12/2020, 10:33:19 AM] Loaded plugin: "homebridge-myq2"
[Homebridge] [4/12/2020, 10:33:19 AM] Registering platform "homebridge-myq2.MyQ2"
[Homebridge] [4/12/2020, 10:33:20 AM] Loaded plugin: "homebridge-samsung-tizen"
[Homebridge] [4/12/2020, 10:33:20 AM] Registering platform "homebridge-samsung-tizen.SamsungTizen"
[Homebridge] [4/12/2020, 10:33:21 AM] Loaded plugin: "homebridge-smartthings-v2"
[Homebridge] [4/12/2020, 10:33:21 AM] Registering platform "homebridge-smartthings-v2.SmartThings-v2"
[Homebridge] [4/12/2020, 10:33:21 AM] Error Loading Plugin "homebridge-zp"
[Homebridge] [4/12/2020, 10:33:21 AM] Loading 5 platforms...
[Homebridge] [4/12/2020, 10:33:21 AM] [SamsungTizen] Initializing SamsungTizen platform...
[Homebridge] [4/12/2020, 10:33:21 AM] [SmartThings-v2] Initializing SmartThings-v2 platform...
[Homebridge] INFO: Homebridge Version: 2.4
[Homebridge] INFO: SmartThings-v2 Plugin Version: 2.3.2
[Homebridge] INFO: Sentry MachineId: 9a4959bb7b759e0f16a3bbad494cbc0ae5d97058959ac280584593c22912783a
[Homebridge] INFO: Checking Package Version for Updates...
[Homebridge] [4/12/2020, 10:33:21 AM] [Camera ffmpeg] Initializing Camera-ffmpeg platform...
[Homebridge] [4/12/2020, 10:33:21 AM] [Indera Mills] Initializing MyQ2 platform...
[Homebridge] [4/12/2020, 10:33:21 AM] Error: The requested platform 'ZP' was not registered by any plugin.
    at API.platform (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/api.js:115:19)
    at Server._loadPlatforms (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:283:47)
    at Server.run (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:74:14)
    at module.exports (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/cli.js:90:12)
    at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/bin/homebridge:10:63)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
[Homebridge] ERROR: uncaughtException: The requested platform 'ZP' was not registered by any plugin.
[Homebridge] Error: The requested platform 'ZP' was not registered by any plugin.
[Homebridge] at API.platform (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/api.js:115:19)
[Homebridge] at Server._loadPlatforms (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:283:47)
[Homebridge] at Server.run (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:74:14)
[Homebridge] at module.exports (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/cli.js:90:12)
[Homebridge] at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/bin/homebridge:10:63)
[Homebridge] at Module._compile (internal/modules/cjs/loader.js:778:30)
[Homebridge] at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
[Homebridge] at Module.load (internal/modules/cjs/loader.js:653:32)
[Homebridge] at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
[Homebridge] at Function.Module._load (internal/modules/cjs/loader.js:585:3)
[Homebridge] [4/12/2020, 10:33:21 AM] Got SIGTERM, shutting down service...
[Homebridge] [4/12/2020, 10:36:55 AM] Loaded config.json with 0 accessories and 5 platforms.
[Homebridge] [4/12/2020, 10:36:58 AM] Loaded plugin: "homebridge-camera-ffmpeg"
[Homebridge] [4/12/2020, 10:36:58 AM] Registering platform "homebridge-camera-ffmpeg.Camera-ffmpeg"
[Homebridge] [4/12/2020, 10:36:58 AM] Loaded plugin: "homebridge-myq2"
[Homebridge] [4/12/2020, 10:36:58 AM] Registering platform "homebridge-myq2.MyQ2"
[Homebridge] [4/12/2020, 10:36:58 AM] Loaded plugin: "homebridge-samsung-tizen"
[Homebridge] [4/12/2020, 10:36:58 AM] Registering platform "homebridge-samsung-tizen.SamsungTizen"
[Homebridge] [4/12/2020, 10:36:59 AM] Loaded plugin: "homebridge-smartthings-v2"
[Homebridge] [4/12/2020, 10:36:59 AM] Registering platform "homebridge-smartthings-v2.SmartThings-v2"
[Homebridge] [4/12/2020, 10:36:59 AM] Error Loading Plugin "homebridge-zp"
[Homebridge] [4/12/2020, 10:36:59 AM] Loading 5 platforms...
[Homebridge] [4/12/2020, 10:36:59 AM] [SamsungTizen] Initializing SamsungTizen platform...
[Homebridge] [4/12/2020, 10:36:59 AM] [SmartThings-v2] Initializing SmartThings-v2 platform...
[Homebridge] INFO: Homebridge Version: 2.4
[Homebridge] INFO: SmartThings-v2 Plugin Version: 2.3.2
[Homebridge] INFO: Sentry MachineId: 9a4959bb7b759e0f16a3bbad494cbc0ae5d97058959ac280584593c22912783a
[Homebridge] INFO: Checking Package Version for Updates...
[Homebridge] [4/12/2020, 10:37:00 AM] [Camera ffmpeg] Initializing Camera-ffmpeg platform...
[Homebridge] [4/12/2020, 10:37:00 AM] [Indera Mills] Initializing MyQ2 platform...
[Homebridge] [4/12/2020, 10:37:00 AM] Error: The requested platform 'ZP' was not registered by any plugin.
    at API.platform (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/api.js:115:19)
    at Server._loadPlatforms (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:283:47)
    at Server.run (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:74:14)
    at module.exports (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/cli.js:90:12)
    at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/bin/homebridge:10:63)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
[Homebridge] ERROR: uncaughtException: The requested platform 'ZP' was not registered by any plugin.
[Homebridge] Error: The requested platform 'ZP' was not registered by any plugin.
[Homebridge] at API.platform (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/api.js:115:19)
[Homebridge] at Server._loadPlatforms (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:283:47)
[Homebridge] at Server.run (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:74:14)
[Homebridge] at module.exports (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/cli.js:90:12)
[Homebridge] at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/bin/homebridge:10:63)
[Homebridge] at Module._compile (internal/modules/cjs/loader.js:778:30)
[Homebridge] at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
[Homebridge] at Module.load (internal/modules/cjs/loader.js:653:32)
[Homebridge] at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
[Homebridge] at Function.Module._load (internal/modules/cjs/loader.js:585:3)
[Homebridge] [4/12/2020, 10:37:00 AM] Got SIGTERM, shutting down service...
[Homebridge] [4/12/2020, 10:37:18 AM] Loaded config.json with 0 accessories and 5 platforms.
[Homebridge] [4/12/2020, 10:37:20 AM] Loaded plugin: "homebridge-camera-ffmpeg"
[Homebridge] [4/12/2020, 10:37:20 AM] Registering platform "homebridge-camera-ffmpeg.Camera-ffmpeg"
[Homebridge] [4/12/2020, 10:37:20 AM] Loaded plugin: "homebridge-myq2"
[Homebridge] [4/12/2020, 10:37:20 AM] Registering platform "homebridge-myq2.MyQ2"
[Homebridge] [4/12/2020, 10:37:21 AM] Loaded plugin: "homebridge-samsung-tizen"
[Homebridge] [4/12/2020, 10:37:21 AM] Registering platform "homebridge-samsung-tizen.SamsungTizen"
[Homebridge] [4/12/2020, 10:37:22 AM] Loaded plugin: "homebridge-smartthings-v2"
[Homebridge] [4/12/2020, 10:37:22 AM] Registering platform "homebridge-smartthings-v2.SmartThings-v2"
[Homebridge] [4/12/2020, 10:37:22 AM] Error Loading Plugin "homebridge-zp"
[Homebridge] [4/12/2020, 10:37:22 AM] Loading 5 platforms...
[Homebridge] [4/12/2020, 10:37:22 AM] [SamsungTizen] Initializing SamsungTizen platform...
[Homebridge] [4/12/2020, 10:37:22 AM] [SmartThings-v2] Initializing SmartThings-v2 platform...
[Homebridge] INFO: Homebridge Version: 2.4
[Homebridge] INFO: SmartThings-v2 Plugin Version: 2.3.2
[Homebridge] INFO: Sentry MachineId: 9a4959bb7b759e0f16a3bbad494cbc0ae5d97058959ac280584593c22912783a
[Homebridge] INFO: Checking Package Version for Updates...
[Homebridge] [4/12/2020, 10:37:23 AM] [Camera ffmpeg] Initializing Camera-ffmpeg platform...
[Homebridge] [4/12/2020, 10:37:23 AM] [Indera Mills] Initializing MyQ2 platform...
[Homebridge] [4/12/2020, 10:37:23 AM] Error: The requested platform 'ZP' was not registered by any plugin.
    at API.platform (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/api.js:115:19)
    at Server._loadPlatforms (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:283:47)
    at Server.run (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:74:14)
    at module.exports (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/cli.js:90:12)
    at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/bin/homebridge:10:63)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
[Homebridge] ERROR: uncaughtException: The requested platform 'ZP' was not registered by any plugin.
[Homebridge] Error: The requested platform 'ZP' was not registered by any plugin.
[Homebridge] at API.platform (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/api.js:115:19)
[Homebridge] at Server._loadPlatforms (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:283:47)
[Homebridge] at Server.run (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:74:14)
[Homebridge] at module.exports (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/cli.js:90:12)
[Homebridge] at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/bin/homebridge:10:63)
[Homebridge] at Module._compile (internal/modules/cjs/loader.js:778:30)
[Homebridge] at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
[Homebridge] at Module.load (internal/modules/cjs/loader.js:653:32)
[Homebridge] at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
[Homebridge] at Function.Module._load (internal/modules/cjs/loader.js:585:3)
[Homebridge] [4/12/2020, 10:37:23 AM] Got SIGTERM, shutting down service...
npm
 WARN winston-daily-rotate-file@4.4.2 requires a peer of winston@^3 but none is installed. You must install peer dependencies yourself.
removed 17 packages and audited 1311 packages in 12.098s

18 packages are looking for funding
  run `npm fund` for details
found 1 low severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
[4/12/2020, 10:37:50 AM] "homebridge-zp" package removed.

```

**Comment by ebaauw** [comment]
Upgrade homebridge to 0.4.53 or remain on previous version of homebridge-zp.

**Comment by RaoulHk** [comment]
Same Problem here. But  HOOBS uses  0.4.50 and there Is no new HOOBS Version To Download.

**Comment by jpjandrucko** [comment]
This is a great plugin but it moves faster than these out of the box services can keep up with.  before updating this plugin make sure you check the dependencies.  We need to hit up Hoobs to update.

**Comment by donavanbecker** [comment]
Another option would be to use regular homebridge which is the latest homebridge.

https://github.com/homebridge/homebridge/wiki

**Comment by jpjandrucko** [comment]
Hoobs users - roll back to .23

open terminal and run the below. HOOBS is working on an update.

cd ~/.hoobs
npm install homebridge-zp@1.0.23

**Comment by turnepf** [comment]
1.0.26 is now working in HOOBS.
