### ISSUE TITLE
Error when adding TV Accessoire

### ISSUE THREAD

**Issue by dewoert** [ebaauw/homebridge-zp#134]
#### Issue
When i try to add a TV accessoire, HomeBride crashes with following error:
`[4/30/2020, 7:32:15 AM] [Symfonisk] Symfonisk Keuken L: identify
[4/30/2020, 7:32:15 AM] TypeError: callback is not a function
    at Tv._identify (/homebridge/node_modules/homebridge-zp/node_modules/homebridge-lib/lib/AccessoryDelegate.js:146:5)
    at PlatformAccessory.emit (events.js:310:20)
    at Accessory.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/platformAccessory.js:38:18)
    at Accessory.emit (events.js:310:20)
    at Accessory.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/EventEmitter.js:59:38)
    at Accessory._this._identificationRequest (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Accessory.js:148:23)
    at Identify.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Accessory.js:1081:23)
    at Identify.emit (events.js:310:20)
    at Identify.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/EventEmitter.js:59:38)
    at Identify.Characteristic._this.setValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Characteristic.js:349:23)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Accessory.js:940:36
    at Array.forEach (<anonymous>:null:null)
    at Accessory._this._handleSetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Accessory.js:808:18)
    at HAPServer.emit (events.js:310:20)
    at HAPServer.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/EventEmitter.js:59:38)
    at HAPServer._this._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/HAPServer.js:851:23)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/HAPServer.js:240:39)
    at IncomingMessage.emit (events.js:310:20)
    at endReadableNT (_stream_readable.js:1187:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)`

Have installed a new Docker with HomeBridge, v1.0.3
Most Plugins seem te work, but i can not get ZP working.:
Config:
        {
            "name": "Symfonisk",
            "brightness": true,
            "excludeAirPlay": false,
            "leds": false,
            "service": "light",
            "speakers": false,
            "tv": true,
            "platform": "ZP"
        },

Extra info from the log:
[4/30/2020, 7:32:28 AM] [Symfonisk] listening on http://192.168.x.x:35699/notify
[4/30/2020, 7:32:28 AM] [Symfonisk] RINCON_347E5CF665EE01400 [Symfonisk Keuken (L)]: associated zone player
[4/30/2020, 7:32:28 AM] [Symfonisk] found 2 zone players in 1 zones
[4/30/2020, 7:32:28 AM] [Symfonisk] └─ Symfonisk Keuken (L+R)
[4/30/2020, 7:32:28 AM] [Symfonisk]    ├─ RINCON_347E5CF665EE01400 [Symfonisk Keuken (L)]: Sonos SYMFONISK (S21) (master, airPlay)
[4/30/2020, 7:32:28 AM] [Symfonisk]    └─ RINCON_347E5C37371601400 [Symfonisk Keuken (R)]: Sonos SYMFONISK (S21) (slave)
[4/30/2020, 7:32:28 AM] [Symfonisk] Symfonisk Keuken L: set Serial Number to "TV_347E5CF665EE01400"
[4/30/2020, 7:32:28 AM] [Symfonisk] Symfonisk Keuken L: set Manufacturer to "Sonos"
[4/30/2020, 7:32:28 AM] [Symfonisk] Symfonisk Keuken L: set Model to "SYMFONISK (S21)"
[4/30/2020, 7:32:28 AM] [Symfonisk] Symfonisk Keuken L: set Firmware Revision to "11.1"
[4/30/2020, 7:32:28 AM] [Symfonisk] Symfonisk Keuken TV: set Active to 0
[4/30/2020, 7:32:28 AM] [Symfonisk] Symfonisk Keuken TV: set Configured Name to "Symfonisk Keuken Sonos"
[4/30/2020, 7:32:28 AM] Symfonisk Keuken L is running on port 35773.
[4/30/2020, 7:32:28 AM] Please add [Symfonisk Keuken L] manually in Home app. Setup Code: 031-45-154
[4/30/2020, 7:32:28 AM] [Symfonisk] Symfonisk Keuken TV: input sources: ["538 Verrückte Stunden","Classics Only - Tilburg & Breda","Radio 8FM Tilburg 88.8 (Classic Hits)","Verrückte Stunde","Sonos Chime"]
[4/30/2020, 7:32:28 AM] [Symfonisk] Symfonisk Keuken TV: set Active Identifier to "Classics Only - Tilburg & Breda"

**Comment by ebaauw** [comment]
What version of homebridge-zp do you use?

**Comment by dewoert** [comment]
homebridge-zp v1.0.27
When adding it in HomeKit on my iPhone, the error also appears when i tick on "Identify accessoire".
I waited until HomeBridge rebooted, and after that i could complete the wizard, TV-accessoire is now added in HomeKit, but in HomeBridge there is no icon visible

**Comment by ebaauw** [comment]
Fixed in homebridge-lib.  If you re-install homebridge-zp, it should pickup the new version of homebridge-lib.

> in HomeBridge there is no icon visible

You mean in Homebridge Config UI X?  I don't know if they support television accessories.  Somehow Apple hides them from other HomeKit apps; you can only see them in Home.
