### ISSUE TITLE
Error with zp cli

### ISSUE THREAD

**Issue by johnluber** [ebaauw/homebridge-zp#140]
Running version 1.0.35 on Ubuntu 20.04 LTS I get an error when I execute the command.

$ /usr/bin/zp -H workshop-sonos volume 0

zp volume: error: TypeError: format: not a string or Error object
    at Main._log (/usr/lib/node_modules/homebridge-zp/node_modules/homebridge-lib/lib/CommandLineTool.js:229:13)
    at Main.print (/usr/lib/node_modules/homebridge-zp/node_modules/homebridge-lib/lib/CommandLineTool.js:196:10)
    at Main.valueCommand (/usr/lib/node_modules/homebridge-zp/cli/zp.js:959:10)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Main.main (/usr/lib/node_modules/homebridge-zp/cli/zp.js:558:7) Issue

**Comment by ebaauw** [comment]
Indeed.  The volume does seem to change anyways.  Same error for setting other numeric values (e.g. bass, treble).

**Comment by johnluber** [comment]
Cool.  Wanted to make sure you were aware.  And, yes, the volume does appear to change even with the error.

**Comment by johnluber** [comment]
Fix works!  Thanks!
