### ISSUE TITLE
Some starts of homebridge end up with a error message "Cannot read property 'zpClient' of undefined"

### ISSUE THREAD

**Issue by Zer0x00** [ebaauw/homebridge-zp#160]
#### Issue

Some starts of homebridge end up with a error message (please see log)
It does not kill homebridge or anything but it is there.

I didn't append a debug log since I have no time to setup a clean environement where only homebridge-zp runs but will do it afterwards if required for further analysis.

#### Log Messages

```
[19/01/2021, 16:27:01] [HB Supervisor] Restarting Homebridge...
[19/01/2021, 16:27:01] [HB Supervisor] Starting Homebridge with extra flags: -I
[19/01/2021, 16:27:01] [HB Supervisor] Started Homebridge v1.3.0-beta.47 with PID: 13055
Initializing HAP-NodeJS v0.9.0-beta.115...
[19/01/2021, 16:27:05] Loaded config.json with 8 accessories and 5 platforms.
[19/01/2021, 16:27:06] ---
[...]
[19/01/2021, 16:27:20] ---
[19/01/2021, 16:27:21] Loaded plugin: homebridge-zp@1.1.4
[19/01/2021, 16:27:21] Registering platform 'homebridge-zp.Lib'
[19/01/2021, 16:27:21] Registering platform 'homebridge-zp.ZP'
[19/01/2021, 16:27:21] Registering platform 'homebridge-zp.ZPS1'
[19/01/2021, 16:27:21] ---
[19/01/2021, 16:27:21] Loading 5 platforms...
[19/01/2021, 16:27:21] [Config] Initializing config platform...
[19/01/2021, 16:27:21] [Config] Running in Service Mode
[19/01/2021, 16:27:21] [Sonos] Initializing ZP platform...
[19/01/2021, 16:27:21] [Sonos] homebridge-zp v1.1.4, node v14.15.4, homebridge v1.3.0-beta.47, homebridge-lib v4.8.4
[19/01/2021, 16:27:21] [Sonos] warning: not using recommended node v14.15.2 LTS
[19/01/2021, 16:27:26] Loading 8 accessories...
[19/01/2021, 16:27:27] [Sonos] restored 1 accessories from cache
Preparing Advertiser for 'Homebridge 72CF' using ciao backend!
Setup Payload:
X-HM://0024CNB4WHK55
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ XXX-XX-XXX │     
    └────────────┘     
                       
Starting to advertise 'Homebridge 72CF' using ciao backend!
[19/01/2021, 16:27:27] Homebridge v1.3.0-beta.47 is running on port 51826.
[19/01/2021, 16:27:28] [Sonos] warning: heartbeat 0, drift 486
[19/01/2021, 16:27:28] [Sonos] listening on http://192.168.0.100:44621/notify
[19/01/2021, 16:27:28] [Sonos] RINCON_48A6B8B59D1801400 [Wohnzimmer]: associated S2 zone player
[19/01/2021, 16:27:29] [Sonos] found 4 S2 zone players in 1 zones
[19/01/2021, 16:27:29] [Sonos] └─ Wohnzimmer (+Sub+RS+LS)
[19/01/2021, 16:27:29] [Sonos]    ├─ RINCON_48A6B8B59D1801400 [Wohnzimmer]: Sonos Arc (S19) (master, airPlay, tvIn)
[19/01/2021, 16:27:29] [Sonos]    ├─ RINCON_542A1B20BE2401400 [Sub (Sub)]: Sonos Sub (S26) (satellite)
[19/01/2021, 16:27:29] [Sonos]    ├─ RINCON_5CAAFDB22BA401400 [Wohnzimmer (RS)]: Sonos One SL (S22) (satellite)
[19/01/2021, 16:27:29] [Sonos]    └─ RINCON_5CAAFDB22BEC01400 [Wohnzimmer (LS)]: Sonos One SL (S22) (satellite)
[19/01/2021, 16:27:30] [Sonos] Sonos: error: TypeError: Cannot read property 'zpClient' of undefined
    at CharacteristicDelegate.getter [as _getter] (/usr/lib/node_modules/homebridge-zp/lib/ZpService.js:107:60)
    at CharacteristicDelegate._onGet (/usr/lib/node_modules/homebridge-zp/node_modules/homebridge-lib/lib/CharacteristicDelegate.js:310:26)
    at Characteristic.emit (events.js:315:20)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1404:14
    at new Promise (<anonymous>)
    at Characteristic.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1402:12)
    at step (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
[19/01/2021, 16:27:30] [Sonos] Sonos: get Remaining Duration: return 0s
[19/01/2021, 16:27:34] [Sonos] warning: heartbeat 6, drift 265
[19/01/2021, 16:28:44] [Sonos] Sonos: get Remaining Duration: return 0s
```

#### Debug Files
Will post if required.

**Comment by ebaauw** [comment]
It seems to be a timing issue.  Do you restart Homebridge while a HomeKit app is open on the detailed screen of the Sonos player?  HomeKit is trying to read the remaining time of the sleep timer.  Homebridge ZP tries to get this from the coordinator of the zone group, but that hasn't been set yet, probably because no `GroupManagementEvent` has been received.

The good news: the error is guarded, so Homebridge ZP continues to operate normally.

The bad news: I probably need to refactor the whole startup logic to fix this.  That's needed to support multiple households anyways, but it's kinda tricky.  Might take a while.

**Comment by Zer0x00** [comment]
Tried to force the error by changing the sound value during the restart, but no luck this time.
I can't say when exactly this happens because it does not happen every time. 

Maybe my wife is doing sth. while I'm restarting homebridge, kinda tricky to know since she can't say when exactly she was controlling the Arc ^-^

Happened so far 10 times since upgrading to the beta homebridge, before I can't remember that the error showed up even a single time.

Since it does not affect anything it isn't urgent, but wanted you to know about the error.

Thanks!

**Comment by ebaauw** [comment]
Maybe it’s the home hub connecting to Homebridge a bit earlier with the latest Homebridge beta.

**Comment by ebaauw** [comment]
Now seeing this for all my zone players in homebridge@1.3.0-beta.47.

**Comment by Supereg** [comment]
The `/accessories` call will now also contact the read handler of an characteristic.
Those calls are typically made after startup (especially when the current configuration number has changed).
Maybe that somehow impacts your logic?

**Comment by ebaauw** [comment]
Ah, that explains why the call is suddenly made a lot earlier.  The `get` handler (now wrongly) assumes Homebridge ZP has fully initialised.  I already adding a check whether is has, and that seems to address the issue.

Does the `/accessories` response contain the characteristic values?  Has this changed, or did HAP-NodeJS simply return the default values before?

**Comment by Supereg** [comment]
> Does the `/accessories` response contain the characteristic values? Has this changed, or did HAP-NodeJS simply return the default values before?

Yeah, previously HAP-NodeJS just returned the current value for the characteristic (which was the default value when `/accessories` happens after startup, so something like `0`, `""`, `false`, whatever fits the unit).
This change was done so HAP-NodeJS would deliver meaningful values for `/accessories`, specifically on startup, where no value is known, as `/accessories` is essentially a read.

As a restart would lead to a storm of controllers accessing `/accessories`, it will actually not always call the read handler. Some homebridge plugins have a tendency to kick off expensive operations on the `get` handler. Thus it will use the cached values if the `get` handler was called 40 seconds ago (as of a `/accessories`). At least that is the current approach.

I wonder if this might have more serious implications on plugins.

**Comment by ebaauw** [comment]
Not sure.  Normally, a plugin shouldn’t do any I/O request on `get`, but return the (computed) value from cache.  This is an uncommon case: _Remaining Time_ (for the sleep timer) changes every second, so it needs to be retrieved from the zone player (as I don’t want to implement a shadow timer in my plugin).  Returning the cached value from up to 40s ago doesn’t seem right.  1 or maybe 2 seconds max, I would think.

**Comment by ebaauw** [comment]
Fixed in v1.1.6.

**Comment by Supereg** [comment]
@ebaauw agree, the timeout is a bit arbitrarily chosen. Gonna adapt that.

**Comment by Zer0x00** [comment]
I had no more issues since the fix, thanks!
