### ISSUE TITLE
Error code in log

### ISSUE THREAD

**Issue by daxterone** [ebaauw/homebridge-zp#162]
#### Issue
I don't know if this is a problem sonos package but homebridge throws out this error message:

#### Log Messages
```
[1/30/2021, 2:56:40 PM] [**_Sonos_**] error: unhandled rejection: Error: Write 0x04cf8cdf3c7dd91f/1 aqaraOpple({"mode":1}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":4447,"transactionSequenceNumber":null}) failed (Data request failed with error: 'MAC transaction expired' (240))
    at ZStackAdapter.<anonymous> (/usr/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:367:23)
    at Generator.next (<anonymous>)
[homebridge.log](https://github.com/ebaauw/homebridge-zp/files/5898121/homebridge.log)

    at fulfilled (/usr/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:24:58)
```

**Comment by ebaauw** [comment]
Looks like `homebridge-zigbee-nt` is throwing an unhandled rejection.  Homebridge ZP is only catching the error, so Homebridge (or rather NodeJS won't crash).
