### ISSUE TITLE
Illegal value for Track reported in Homebridge v1.3.0

### ISSUE THREAD

**Issue by jsiegenthaler** [ebaauw/homebridge-zp#165]
#### Issue

Illegal value for Track reported in Homebridge v1.3.0
Using homebridge-zp v1.1.6
You could consider truncating the characteristic value.

#### Log Messages

```
[20/02/2021, 10:39:59] [homebridge-zp] This plugin generated a warning from the characteristic 'Track': characteristic was supplied illegal value: string 'Radio SRF 3 - srf3.ch - studio@srf3.ch - facebook/srf3 - twitter @srf3 - instagram/srf3' exceeded max length of 64. See https://git.io/JtMGR for more info.
```

**Comment by jsiegenthaler** [comment]
Hello @ebaauw 

I logged the warning with Debug mode on:

```
[24/02/2021, 06:46:52] [homebridge-zp] This plugin generated a warning from the characteristic 'Track': characteristic was supplied illegal value: string 'Radio SRF 3 - srf3.ch - studio@srf3.ch - facebook/srf3 - twitter @srf3 - instagram/srf3' exceeded max length of 64. See https://git.io/JtMGR for more info.
[24/02/2021, 06:46:52] [homebridge-zp] Error: 
    at Characteristic.characteristicWarning (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2164:105)
    at Characteristic.validateUserInput (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2088:16)
    at Characteristic.updateValue (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1365:20)
    at CharacteristicDelegate.set value [as value] (/usr/lib/node_modules/homebridge-zp/node_modules/homebridge-lib/lib/CharacteristicDelegate.js:275:28)
    at Object.set (/usr/lib/node_modules/homebridge-zp/node_modules/homebridge-lib/lib/ServiceDelegate.js:258:50)
    at Sonos.handleMediaRendererAVTransportEvent (/usr/lib/node_modules/homebridge-zp/lib/ZpService.js:479:32)
    at ZpClient.<anonymous> (/usr/lib/node_modules/homebridge-zp/lib/ZpService.js:41:18)
    at ZpClient.emit (events.js:327:22)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-zp/lib/ZpListener.js:100:22)
    at runMicrotasks (<anonymous>)
```

**Comment by ebaauw** [comment]
Thanks for the report.  I'll have a look at this for the next version.  Not sure yet whether to increase the length of `Track` or to slice the reported value.  I don't think you'll be able to see the entire string in a HomeKit app?

**Comment by jsiegenthaler** [comment]
Hi. I think truncating the string would be the simplest. I don't know of any HomeKit app that could display 64 characters anyway...

**Comment by ebaauw** [comment]
In v.1.1.7.
