### ISSUE TITLE
Error using browse

### ISSUE THREAD

**Issue by kjal203** [ebaauw/homebridge-zp#188]
Using latest version of zp gives me the following when using browse command:

zp browse: error: SyntaxError: initTopology() not yet called
    at ZpClient.checkInitTopology (/usr/local/lib/node_modules/homebridge-zp/lib/ZpClient.js:528:13)
    at ZpClient.get airPlay [as airPlay] (/usr/local/lib/node_modules/homebridge-zp/lib/ZpClient.js:549:10)
    at Main.browse (/usr/local/lib/node_modules/homebridge-zp/cli/zp.js:935:25)
    at Main.main (/usr/local/lib/node_modules/homebridge-zp/cli/zp.js:691:39)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

I‘d be glad to assist with more info, but pls tell me how to provide.

**Comment by ebaauw** [comment]
Thanks for reporting.  Fixed in v1.4.10.

**Comment by kjal203** [comment]
Wow, thanks!
