### ISSUE TITLE
Latest Version Not installing since updating node to 16.x

### ISSUE THREAD

**Issue by adavison007** [ebaauw/homebridge-zp#192]
I've just updated node to 16.13.1 and now when I try to install you latest code today I get the following, is this an error with my node install?

CMD: sudo -E -n npm install -g homebridge-zp@latest

TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/socks-proxy-agent/dist/agent.js:114:44)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/socks-proxy-agent/dist/index.js:5:33)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/make-fetch-happen/lib/agent.js:161:25)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)

Command failed. Please review log for details.

**Comment by ebaauw** [comment]
Yes, see https://github.com/homebridge/homebridge/issues/3002.

**Comment by adavison007** [comment]
@ebaauw Thanks for the response, I just did this and everything is now working including the latest version of your plugin, big thanks as always.
<img width="898" alt="Screenshot 2022-01-02 at 16 03 12" src="https://user-images.githubusercontent.com/47482260/147881661-83b61951-8520-4af0-8a3a-1ad89ea08391.png">
