### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'zoneGroupShortName')

### ISSUE THREAD

**Issue by jsiegenthaler** [ebaauw/homebridge-zp#209]
#### Issue

TypeError: Cannot read properties of undefined (reading 'zoneGroupShortName')

Error was thrown when the Sonos device was turned off at the mains and thus unreachable

#### Log Messages

```
[26/11/2023, 18:58:03] [Sonos] Office Sonos: Active: set to 0
[26/11/2023, 18:58:03] [Sonos] Office Sonos: Status Fault: set to 1
[26/11/2023, 18:58:03] [Sonos] Input 1: Configured Name: set to "n/a" (from "Input 1")
[26/11/2023, 18:58:03] [Sonos] n/a: Name: set to "n/a" (from "Input 1")
[26/11/2023, 18:58:03] [Sonos] error: RINCON_5CAAFDCF9FB401400: [192.168.0.162]: TypeError: Cannot read properties of undefined (reading 'zoneGroupShortName')
    at Tv.updateGroupInputSource (/var/lib/homebridge/node_modules/homebridge-zp/lib/ZpService.js:1199:43)
    at Tv.favouritesUpdated (/var/lib/homebridge/node_modules/homebridge-zp/lib/ZpService.js:1136:10)
    at new Tv (/var/lib/homebridge/node_modules/homebridge-zp/lib/ZpService.js:1097:10)
    at new Tv (/var/lib/homebridge/node_modules/homebridge-zp/lib/ZpAccessory.js:343:22)
    at ZpPlatform.logTopology (/var/lib/homebridge/node_modules/homebridge-zp/lib/ZpPlatform.js:473:41)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[26/11/2023, 18:58:03] [Sonos] Office Sonos: Status Fault: set to 0 (from 1)
```

**Comment by ebaauw** [comment]
Does the error happing after restarting Homebridge, or while Homebridge was running (for a longer time)?  Was the speaker turned off during Homebridge startup, or was Homebridge restarted after the speaker was turned off?

**Comment by jsiegenthaler** [comment]
The sequence of events was like this:
1. Two of my Sonos speakers went off line. 
2. Debugging showed they were not visible in the Sonos app (app could not connect) and not visible on mDNS (using the iOS Discovery app). 
3. I power cycled the speakers which made no difference and then noted that Homebridge-zp was having issues and logging the unhandled error that I reported.
4. At that stage Homebridge had been running for a few hours as I had restarted it earlier in the day.
5. I left the issue untouched overnight.
6. Today I rebooted my main router and that cleared the issue, the Sonos speakers came back online. 
7. I then (foolishly?) also truncated my Homebridge logs.

Unfortunately due to log truncation I don't have any logs from yesterday (unless they get archived automatically somewhere...)

I note the error thrown was on ZpService.js:1199:43 
`configuredName = 'Join ' + zpClient.zoneGroupShortName`
Clearly, the object zpClient was undefined and thus the zoneGroupShortName property could not be read.
You could add some robustness in your code by something like:
 `const zpClient = this.platform.zpClients[platformCoordinatorId] || ''`
So even though the property might not exist, at least the object is defined.
Of course, the best solution will be the one you decide on, not the one I propose :)

**Comment by ebaauw** [comment]
> not visible on mDNS (using the iOS Discovery app).

Sonos uses UPnP for discovery.  mDNS is used for Airplay 2, but Sonos themselves don't use it.  Older zone players that don't support AirPlay won't show on mDNS.

> You could add some robustness in your code by something like:

I'll address the `TypeError` for sure, but that's more like a workaround.  It looks like the platform coordinator went missing, and consequently, Homebridge ZP didn't create a ZpClient for it on restart.  I think for a structural solution, I need to clear the platform coordinator, if it's no longer available.  Not the kind of use cases that are easy to test, unfortunately.

**Comment by jsiegenthaler** [comment]
Thanks for the feedback.
Indeed, you need to make **`_sonos._tcp.`** your friend :)

If I can ever reproduce the situation, I'll let you know. In the meantime, good luck!

**Comment by ebaauw** [comment]
In v1.4.40.
