### ISSUE TITLE
http status 412 Precondition Failed

### ISSUE THREAD

**Issue by matbe81** [ebaauw/homebridge-zp#217]
#### Issue
Tons of log error messages after upgrade to Ubuntu 24.04 LTS

#### Log Messages
```
[5/23/2024, 11:37:46 PM] [Sonos] Salle à manger L: request 6380: SUBSCRIBE /MediaRenderer/RenderingControl/Event
[5/23/2024, 11:37:46 PM] [Sonos] Salle à manger L: warning: request 6380: http status 412 Precondition Failed
[5/23/2024, 11:37:46 PM] [Sonos] Salle à manger Speakers: error: SyntaxError: open() not yet called
    at ZpClient.subscribe (/usr/lib/node_modules/homebridge-zp/lib/ZpClient.js:1020:13)
    at ZpClient.subscribe (/usr/lib/node_modules/homebridge-zp/lib/ZpClient.js:1045:21)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Master.<anonymous> (/usr/lib/node_modules/homebridge-zp/lib/ZpService.js:749:9)
```

**Comment by ebaauw** [comment]
"Precondition Failed" typically means the zone player won't accept a subscription renewal.  Typically because the subscription expired while Homebridge ZP wasn't running.  Did you try power cycling the zone players, and then restarting Homebridge?

**Comment by matbe81** [comment]
Indeed. It's working. Thank you !
