### ISSUE TITLE
TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by jer78** [ebaauw/homebridge-zp#26]
I updated to the latest version but now getting this error which crashes Homebridge...any ideas?

TypeError: Cannot read property '0' of undefined
    at ZPAccessory.<anonymous> (/usr/local/lib/node_modules/homebridge-zp/lib/ZPAccessory.js:294:62)
    at Parser.<anonymous> (/usr/local/lib/node_modules/homebridge-zp/node_modules/xml2js/lib/parser.js:303:18)
    at emitOne (events.js:116:13)
    at Parser.emit (events.js:211:7)
    at SAXParser.onclosetag (/usr/local/lib/node_modules/homebridge-zp/node_modules/xml2js/lib/parser.js:261:26)
    at emit (/usr/local/lib/node_modules/homebridge-zp/node_modules/sax/lib/sax.js:624:35)
    at emitNode (/usr/local/lib/node_modules/homebridge-zp/node_modules/sax/lib/sax.js:629:5)
    at closeTag (/usr/local/lib/node_modules/homebridge-zp/node_modules/sax/lib/sax.js:889:7)
    at SAXParser.write (/usr/local/lib/node_modules/homebridge-zp/node_modules/sax/lib/sax.js:1436:13)
    at Parser.exports.Parser.Parser.parseString (/usr/local/lib/node_modules/homebridge-zp/node_modules/xml2js/lib/parser.js:322:31)

**Comment by ebaauw** [comment]
homebridge-zp is trying to parse the XML returned by the player to determine the song currently playing.  My guess you were playing a source that behaves somewhat differently than the sources I use.  I can encapsulate the code so homebridge/homebridge-zp won’t crash, but I need some more info to prevent the error in the first place:
- What were you playing at the moment homebridge-zp crashed?
- Did you add a this service to your Sonos after updating homebridge-zp?  I don’t see how this crash would be related to any recent change.
- Could you post a screenshot of the Sonos app, showing what’s playing (available controls, track data, ...)?
- Could you attach the output of homebridge -D, see **Troubleshooting** in the README?

**Comment by ebaauw** [comment]
Could you try v0.2.8?  It should issue a warning about unknown track metadata instead of crashing.
