### ISSUE TITLE
Receive error: "uncaught exception" when http request not handled from another plugin

### ISSUE THREAD

**Issue by Tommrodrigues** [ebaauw/homebridge-zp#41]
Hi there,

Thanks for all the work you've put into homebridge-zp, it's been working pretty much perfectly for me for the last few months. However, recently, I have started using [this](https://github.com/goedh452/homebridge-http-sprinkler) plugin to control a relay connected to a NodeMCU which usually works perfectly. The problem comes when the NodeMCU is either offline or unreachable; when this happens I get the following from homebridge followed by homebridge shutting down:

```
[2018-8-8 22:41:22] [Misters] Setting power state to on
[2018-8-8 22:41:26] [ZP] uncaught exception
[2018-8-8 22:41:26] [ZP] Error: connect EHOSTUNREACH 192.168.1.146:80
    at doRequest (/usr/local/lib/node_modules/homebridge-http-sprinkler/node_modules/sync-request/index.js:31:11)
    at HttpSprinkler.setPowerState (/usr/local/lib/node_modules/homebridge-http-sprinkler/index.js:190:13)
    at emitMany (events.js:147:13)
    at Characteristic.Active.emit (events.js:224:7)
    at Characteristic.Active.Characteristic.setValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:320:10)
    at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:871:22)
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._handleSetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:811:8)
    at emitMany (events.js:147:13)
    at HAPServer.emit (events.js:224:7)
[2018-8-8 22:41:26] Got SIGTERM, shutting down Homebridge...
[2018-8-8 22:41:26] [ZP] cleaning up...
[2018-8-8 22:41:31] [ZP] exit
```

As you can see, I believe it is homebridge-zp which is causing homebridge to crash which is not great. I am unsure as to why homebridge-zp causes an exit when this happens as it has nothing to do with the other plugin.

I would really appreciate it if you could help me figure out how to stop this from happening in the future as it is rather inconvenient to have to restart homebridge every time there is some problem to do with the NodeMCU.

Thank you in advance for any help,

Kind regards, Tom

P.S. I have homebridge running on a Raspberry Pi wirelessly. To clarify, there is no issue when there is no issue with the connection to the NodeMCU, this only happens when the NodeMCU is unreachable

**Comment by ebaauw** [comment]
> As you can see, I believe it is homebridge-zp which is causing homebridge to crash

No, homebridge-zp merely reports the crash, but doesn't cause it.

```
[2018-8-8 22:41:26] [ZP] uncaught exception
...
[2018-8-8 22:41:26] Got SIGTERM, shutting down Homebridge...
[2018-8-8 22:41:26] [ZP] cleaning up...
[2018-8-8 22:41:31] [ZP] exit
```
homebridge-zp installs a handler for otherwise uncaught exceptions, to exit homebridge cleanly, so it can cancel the subscriptions with the Sonos players, before nodejs terminates.  It lists the full stack trace of the exception, which is raised by the sync-request module that's included by homebridge-http-sprinkler:
```
[2018-8-8 22:41:26] [ZP] Error: connect EHOSTUNREACH 192.168.1.146:80
   at doRequest (/usr/local/lib/node_modules/homebridge-http-sprinkler/node_modules/sync-request/index.js:31:11)
```
homebridge-http-sprinkler fails to handle this exception:
```
   at HttpSprinkler.setPowerState (/usr/local/lib/node_modules/homebridge-http-sprinkler/index.js:190:13)
```
If you would run homebridge with only that plugin, nodejs would simply crash when NodeMCU is unreachable.

Looking at the [README for sync-request](https://github.com/ForbesLindesay/sync-request#readme), I would definitely run homebridge-http-sprinker in a separate homebridge instance, if at all.

**Comment by Tommrodrigues** [comment]
Thank you for your reply!

I apologise for so quickly coming to the incorrect conclusion that homebridge-zp was the cause of the crash. Strange that homebridge-http-sprinkler is unable to handle this exception. I only have 1 homebridge instance running so it looks like I'll have to move away from homebridge-http-sprinkler which is a shame because it was the only plugin I found which supported the faucet/sprinkler accessory type with http requests. Looks like I'll have to move to something more stable like homebridge-http.

Thanks once again for your help!

Kind regards,
Tom

**Comment by ebaauw** [comment]
> Looks like I'll have to move to something more stable like homebridge-http.

Yeah, homebridge-http uses the asynchronous library `request` (that I also use).  Don't know why they changed that for homebridge-http-sprinkler.

**Comment by Tommrodrigues** [comment]
Shame, I'll file an issue on homebridge-http-sprinkler asking them to fix this.
