### ISSUE TITLE
EADDRINUSE 

### ISSUE THREAD

**Issue by d34vbd5** [ebaauw/homebridge-zp#45]
[2018-9-5 15:08:02] [ZP] uncaught exception
[2018-9-5 15:08:02] [ZP] { Error: listen EADDRINUSE :::51828
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at Server.setupListenHandle [as _listen2] (net.js:1355:14)
    at listenInCluster (net.js:1396:12)
    at Server.listen (net.js:1480:7)
    at PeoplePlatform.startServer (/usr/lib/node_modules/homebridge-people/index.js:120:24)
    at PeoplePlatform.accessories (/usr/lib/node_modules/homebridge-people/index.js:60:14)
    at Server._loadPlatformAccessories (/usr/lib/node_modules/homebridge/lib/server.js:386:20)
    at Server._loadPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:330:16)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:86:36)
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 51828 }

Any idea why thats happening?
Regards

**Comment by ebaauw** [comment]
You’re already running homebridge.
