### ISSUE TITLE
Getting error after upgrade: The requested platform 'ZP' was not registered

### ISSUE THREAD

**Issue by jenssegers** [ebaauw/homebridge-zp#83]
Currently getting this error after upgrading to the latest version:

```
[7/7/2019, 7:32:37 AM] Error: The requested platform 'ZP' was not registered by any plugin.
    at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:134:13)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:327:45)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:90:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
[7/7/2019, 7:32:37 AM] Got SIGTERM, shutting down Homebridge...
```

Running Homebridge as a docker container. Upgraded from 0.4.2 to 0.4.3.

**Comment by ebaauw** [comment]
You need to install homebridge-lib separately, see https://github.com/ebaauw/homebridge-zp#installation and https://github.com/ebaauw/homebridge-zp/releases/tag/v0.4.3.
